#!/usr/local/bin/python2.6

import os, json, base64, subprocess, sys, mimetypes, httplib, re


file = sys.argv.pop()
#file_prefix = re.sub('-.*', '', os.path.splitext(file)[0])
id = sys.argv.pop()

data = {}

os.system("/bin/cp " + file + " " + id + "-original.jpg")
os.system("/usr/local/bin/convert -size 100 " + file + " -thumbnail 100 " + id + "-thumbnail.jpg")
os.system("/usr/local/bin/convert -size 500 " + file + " -thumbnail 500 " + id + "-medium.jpg")
os.system("/usr/local/bin/convert -size 1024 " + file + " -thumbnail 1024 " + id + "-large.jpg")
os.system("/usr/local/bin/convert -size 2048 " + file + " -thumbnail 2048 " + id + "-huge.jpg")

data['_attachments'] = {
    id + "-original.jpg" : {
        "content_type" : mimetypes.guess_type(id + "-original.jpg")[0],
        "data" : base64.b64encode(open(id + "-original.jpg", 'rb').read()),
        },
    id + "-thumbnail.jpg" : {
        "content_type" : mimetypes.guess_type(id + "-thumbnail.jpg")[0],
        "data" : base64.b64encode(open(id + "-thumbnail.jpg", 'rb').read()),
        },
    id + "-medium.jpg" : {
        "content_type" : mimetypes.guess_type(id + "-medium.jpg")[0],
        "data" : base64.b64encode(open(id + "-medium.jpg", 'rb').read()),
        },
    id + "-large.jpg" : {
        "content_type" : mimetypes.guess_type(id + "-large.jpg")[0],
        "data" : base64.b64encode(open(id + "-large.jpg", 'rb').read()),
        },
    id + "-huge.jpg" : {
        "content_type" : mimetypes.guess_type(id + "-huge.jpg")[0],
        "data" : base64.b64encode(open(id + "-huge.jpg", 'rb').read()),
        },
    }


conn = httplib.HTTPConnection("localhost:5984")
conn.request("PUT","/images/" + id,
             json.dumps(data), {"Content-type": "application/json"})
r1 = conn.getresponse()

print r1.status, r1.reason
print r1.read()

