#!/usr/bin/env python

import sys, fileinput, json, httplib, re, os

connexion = httplib.HTTPConnection("localhost:5984")

uri = sys.argv.pop(1)

if re.search("^/[a-zA-Z0-9\-_\.]+$", uri):
    connexion.request("PUT",uri)
else:
    json_data = ""
    for line in fileinput.input():
        json_data = json_data + line
    connexion.request("PUT",uri,
                 json_data, {"Content-type": "application/json"}) 

http_response    = connexion.getresponse()
couchdb_response = http_response.read()

if os.path.exists('_rev') and http_response.reason == "Created": #bump version
    f = open('_rev','w')
    resp = json.loads(couchdb_response)
    f.write(json.dumps(resp["rev"]))

sys.stderr.write(str(http_response.status) + " "
                 + http_response.reason + "\n")
sys.stdout.write(couchdb_response)
