#!/usr/local/bin/python2.6

import sys, fileinput, json, httplib, re

conn = httplib.HTTPConnection("localhost:5984")

uri = sys.argv.pop(1)

if re.search("^/[a-zA-Z0-9\-_\.]+$", uri):
    conn.request("PUT",uri)
else:
    json_data = ""
    for line in fileinput.input():
        json_data = json_data + line
        conn.request("PUT",uri,
                     json_data, {"Content-type": "application/json"}) 

r1 = conn.getresponse()

print r1.status, r1.reason
print r1.read()
