#!/usr/bin/env python

import sys, httplib, getopt, ConfigParser, os

opts, args = getopt.getopt(sys.argv[1:], 'h:p:s:c:')

def usage():
    print "couchcopy -c <config> -s <config section> -h <host> -p <port> /<base>/<ressource> <new_ressource>"

host           = ""
port           = ""
config_file    = ""
config_section = ""


for o, a in opts:
    if o == '-h':
        host = a
    if o == '-p':
        port = a
    if o == '-c':
        config_file = a
    if o == '-s':
        config_section = a

config = ConfigParser.ConfigParser()
if not config_section:
    config_section = 'default'
if not config_file:
    config_file = "~/.couchstuffs"
config.read([os.path.expanduser(config_file)])

if not host:
    host = config.get(config_section, 'host')
if not port:
    port = config.get(config_section, 'port')

connexion = httplib.HTTPConnection(host, port)

connexion.request("COPY", args[0], "", {"Destination": args[1]})

response = connexion.getresponse()
sys.stderr.write(str(response.status) + " "
                 + response.reason + "\n")
sys.stdout.write(response.read())