#!/usr/bin/perl

use strict;
use warnings;
use 5.010;
use JSON;


my $doc_uri = shift @ARGV;
my $doc_json = `curl -sX GET http://localhost:5984/$doc_uri`;
my $json = JSON->new->allow_nonref;
my $perl_data = $json->decode( $doc_json );
my $rev = $perl_data->{'_rev'};

for (@ARGV) {
    (my $filename, my $type) = split ':',`file -i $_`;
    $type =~ s/^ //;
    chomp($type);
    my $result = `curl -sX PUT http://localhost:5984/$doc_uri/$filename?rev=$rev --data-binary \@$filename -H "Content-type: $type"`;
    $perl_data = $json->decode( $result );
    $rev = $perl_data->{'rev'};
    print $result;
}
