#!/usr/local/bin/python2.6

import os, fileinput, json, base64

json_data = ""

for line in fileinput.input():
    json_data = json_data + line

doc = json.loads(json_data)

for key in doc:
    if key != '_attachments':
        f = open(key, 'w')
        f.write(json.dumps(doc[key],indent=4))
    else:
        if not os.path.exists("_attachment"):
            os.makedirs("_attachment")
        for attachment in doc[key]:
            if not "stub" in doc[key][attachment]:
                f = open("_attachment/" + attachment, 'wb')
                data = base64.b64decode(doc[key][attachment]['data'])
                f.write(data)

            
            
