#!/usr/local/bin/python2.6

import sys, json, os, httplib, pprint, urllib, re, mimetypes, base64

uri = sys.argv[1]

json_data = {}

for file in os.listdir("."):
    if not re.search("~$", file) and file != '_attachments':
        f = open(file, "r")
        json_data[file] = json.loads(f.read())
    elif file == '_attachments':
        for attachment in os.listdir('_attachments'):
            mime = mimetypes.guess_type('_attachments' + attachment)[0]
            b = open('_attachments/' + attachment, 'rb')
            content = base64.b64encode(b.read())
            json_data['_attachments'] = {
                attachment : {
                    "content_type" : mime,
                    "data" : content
                    }
                }
        

#json.dumps(json_data)

conn = httplib.HTTPConnection("localhost:5984")

#params = urllib.urlencode(json.dumps(json_data))
#headers = {"Content-type": "application/x-www-form-urlencoded",
#           "Accept": "text/plain"}


conn.request("PUT",uri,
             json.dumps(json_data), {"Content-type": "application/json"})
r1 = conn.getresponse()

print r1.status, r1.reason
print r1.read()

